name: Generate Profile Statistics

on:
  schedule:
    - cron: "17 2 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-statistics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate statistics SVG
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/userstats.svg
          colors: dark
          custom-title: "ZALEK // SIGNATURE 548"
          max-languages: 8
          animated-language-chart: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
